export const APP_NAME = "Pathology Laboratory Management System";

export const ROLES = {
  ADMIN: "ADMIN",
  TECHNICIAN: "TECHNICIAN",
  PATHOLOGIST: "PATHOLOGIST",
  QUALITY_MANAGER: "QUALITY_MANAGER",
};

export const PRIORITY = {
  NORMAL: "NORMAL",
  URGENT: "URGENT",
  STAT: "STAT",
};

export const CASE_STATUS = {
  REGISTERED: "REGISTERED",
  SPECIMEN_COLLECTED: "SPECIMEN_COLLECTED",
  IN_PROCESS: "IN_PROCESS",
  COMPLETED: "COMPLETED",
  REPORTED: "REPORTED",
};

export const SPECIMEN_STATUS = {
  COLLECTED: "COLLECTED",
  RECEIVED: "RECEIVED",
  ACCESSIONED: "ACCESSIONED",
  PROCESSING: "PROCESSING",
  COMPLETED: "COMPLETED",
};

export const BLOCK_STATUS = {
  CREATED: "CREATED",
  GROSSING: "GROSSING",
  EMBEDDING: "EMBEDDING",
  SECTIONING: "SECTIONING",
  COMPLETED: "COMPLETED",
};

export const SLIDE_STATUS = {
  CREATED: "CREATED",
  STAINING: "STAINING",
  STAINED: "STAINED",
  SCANNED: "SCANNED",
  UNDER_REVIEW: "UNDER_REVIEW",
  COMPLETED: "COMPLETED",
};

export const WORKFLOW_STAGES = {
  SPECIMEN_COLLECTION: "SPECIMEN_COLLECTION",
  ACCESSIONING: "ACCESSIONING",
  GROSSING: "GROSSING",
  EMBEDDING: "EMBEDDING",
  SECTIONING: "SECTIONING",
  STAINING: "STAINING",
  SCANNING: "SCANNING",
  PATHOLOGIST_REVIEW: "PATHOLOGIST_REVIEW",
};

export const WORKFLOW_EVENT_STATUS = {
  STARTED: "STARTED",
  COMPLETED: "COMPLETED",
};

export const REPORT_STATUS = {
  DRAFT: "DRAFT",
  FINAL: "FINAL",
};

export const QC_RESULT = {
  PASSED: "PASSED",
  FAILED: "FAILED",
  NEEDS_REVIEW: "NEEDS_REVIEW",
};

export const SPECIMEN_QUALITY = {
  GOOD: "GOOD",
  DAMAGED: "DAMAGED",
  INADEQUATE: "INADEQUATE",
};

export const QC_RATING = {
  GOOD: "GOOD",
  ACCEPTABLE: "ACCEPTABLE",
  POOR: "POOR",
};

export const QC_CHECK_RESULT = {
  PASS: "PASS",
  FAIL: "FAIL",
};

export const PATIENT_GENDER = {
  MALE: "MALE",
  FEMALE: "FEMALE",
  OTHER: "OTHER",
};

export const PATIENT_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  SUSPENDED: "SUSPENDED",
};

export const DOCTOR_STATUS = {
  PENDING_VERIFICATION: "PENDING_VERIFICATION",
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  SUSPENDED: "SUSPENDED",
};
